Web/Web/urls.py
from django.contrib import admin
from django.urls import path
from zxc import views
from django.urls import re_path
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from zxc import urls

urlpatterns = [
    path('', views.index, name='home'),
    path('admin/', admin.site.urls),
    path('', include('zxc.urls')),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('programming_courses/', views.programming_courses, name='programming_courses'),
    path('english_courses/', views.english_courses, name='english_courses'),
    path('musicandcinema/', views.musicandcinema_courses, name='musicandcinema_courses'),
    path('game_courses/', views.game_courses, name='game_courses'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
    path('api/', include('zxc.urls')),
    path('login/', views.login_view, name='login'),
    path('profile/', views.profile_view, name='profile'),
    path('add_course/<int:course_id>/', views.add_course_to_profile, name='add_course_to_profile'),
    path('courses/', views.CourseListView.as_view(), name='course_list'),

] 
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

Web/zxc/urls.py
from django.urls import path, include
from .views import CourseViewSet, SingleCourseView, TeacherViewSet, UserViewSet, SnippetViewSet, CustomAuthToken
from rest_framework.routers import DefaultRouter
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets
from rest_framework.schemas import get_schema_view 
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.urlpatterns import format_suffix_patterns


router = DefaultRouter()
router.register(r'courses', CourseViewSet, basename='course')
router.register(r'teachers', TeacherViewSet, basename='teacher')
router.register(r'users', UserViewSet, basename='user')
router.register(r'snippets', SnippetViewSet, basename='snippet')
router.register(r'v1/courses', CourseViewSet, basename='course-v1')
router.register(r'v2/courses', CourseViewSet, basename='course-v2')
# urlpatterns = router.urls

# Создаем общие маршруты
urlpatterns = [
    path('api-token-auth/', CustomAuthToken.as_view(), name='api_token_auth'),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/docs/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('', include(router.urls)),
]

# Включаем ваши маршруты с помощью	router
urlpatterns += router.urls

# Добавляем суффиксы формата
# urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json', 'html'])

# urlpatterns = [
#     path('courses/', CourseViewSet.as_view({'get': 'list'})),
#     path('courses/<int:pk>/', CourseViewSet.as_view({'get': 'retrieve'})),
# ]

Web/zxc/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import AbstractUser
from pygments.lexers import get_lexer_by_name
from pygments.formatters.html import HtmlFormatter
from pygments import highlight
    

class Teacher(models.Model):
    first_name = models.CharField(max_length=100,
                                help_text="Введите имя преподавателя",
                                verbose_name="Имя преподавателя")
    middle_name = models.CharField(max_length=100,
                                help_text="Введите фамилию преподавателя",
                                verbose_name="Фамилия преподавателя")
    last_name = models.CharField(max_length=100,
                                help_text="Введите отчество преподавателя",
                                verbose_name="Отчество преподавателя")
    specialization = models.CharField(max_length=200,
                                    help_text="Введите специальность преподавателя",
                                    verbose_name="Специальность преподавателя")
    description = models.TextField(help_text="Введите проекты и языки программирования, которые знает преподаватель",
                                    verbose_name="Описание карьеры")
    experience = models.IntegerField(help_text="Введите стаж работы преподавателя в IT-сфере",
                                    verbose_name="Стаж работы")
    photo = models.ImageField(upload_to='images',
                                help_text="Введите фото преподавателя",
                                verbose_name="Фото преподавателя",
                                null=True, blank=True)

    def __str__(self):
        return f"{self.first_name} {self.middle_name} {self.last_name}"

class DurationCourse(models.Model):
    duration = models.IntegerField(help_text="Введите длительность курса",
                                    verbose_name="Длительность курса")

    def __str__(self):
        return str(self.duration)
    
class CustomUser(AbstractUser):
    bio = models.TextField(blank=False)
    email = models.EmailField(unique=True)  # Ensure emails are unique and enforce email format

    def __str__(self):
        return self.username
    
    @property
    def courses(self):
        return self.students.all()
    
class Course(models.Model):
    title = models.CharField(max_length=200,
                             help_text="Введите название курса",
                             verbose_name="Название курса")
    categorycourse = models.CharField(max_length=50,
                                       choices=[('programming', 'Программирование'),
                                                ('english', 'Английский язык'),
                                                ('game', 'Игры'),
                                                ('music_and_cinema', 'Кино и музыка')],
                                       default='programming')
    description = models.TextField(help_text="Введите описание курса",
                                   verbose_name="Описание курса")
    teacher = models.ManyToManyField('Teacher',
                                      help_text="Выберите преподавателя (преподавателей) для курса",
                                      verbose_name="Преподаватель (преподаватели) курса")
    duration = models.ForeignKey('DurationCourse', on_delete=models.CASCADE,
                                  help_text="Введите длительность курса",
                                  verbose_name="Длительность курса")
    students = models.ManyToManyField(CustomUser, blank=True, related_name='courses', help_text='Выберите студентов, записанных на этот курс')
    price = models.DecimalField(decimal_places=2, max_digits=7,
                                help_text="Введите стоимость курса",
                                verbose_name="Стоимость курса",
                                null=True)
    photo = models.ImageField(upload_to='course_photos/',
                              help_text="Введите обложку курса",
                              verbose_name="Обложка курса",
                              null=True)

    def __str__(self):
        return self.title

    def display_teacher(self):
        return ', '.join([teacher.middle_name for teacher in self.teacher.all()])
    
    display_teacher.short_description = "Преподаватели"

class Snippet(models.Model):
    owner = models.ForeignKey(CustomUser, related_name='snippets', on_delete=models.CASCADE)
    code = models.TextField()
    highlighted = models.TextField()
    title = models.CharField(max_length=100, default='A snippet')
    language = models.CharField(max_length=100, default='python')
    linenos = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        lexer = get_lexer_by_name(self.language)
        formatter = HtmlFormatter()
        self.highlighted = highlight(self.code, lexer, formatter)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

Web/zxc/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2', 'bio')

class CustomLoginForm(AuthenticationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'password']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'bio', 'email']

Web/templates/zxc/about.html
{% extends "zxc/base.html" %}
<head>
    {% load static %}
    <style>
        .card {
            flex: 1 1 auto; /* Увеличивает гибкость ширины карточек */
            min-width: 300px; /* Минимальная ширина карточки */
            background-color: wheat;
        }
        .card-deck {
            gap: 20px; /* Расстояние между карточками */
            background-color: wheat;
        }
        .badge-wheat {
            background-color: wheat; /* Цвет фона - пшеничный */
            color: black; /* Текст становится читабельным - черный цвет */
            padding: 10px 15px; /* Отступы */
            border-radius: 5px; /* Закругленные края для красоты */
            font-size: 1rem; /* Размер текста */
        }
        
    </style>
</head>
{% block content %}
<div class="container-fluid text-center">
    <h1>О нас</h1>
    <p>Миссия Online-Курс — дать возможность каждому быть актуальным и востребованным специалистом прямо сейчас. Вне зависимости от возраста и географии.</p>
    
    <div class="my-4">
        <img src="{% static 'images/online.jpg' %}" width="900px" height="400px" alt="Учим">
    </div>

    <h2>Мы предлагаем большой выбор</h2>
    <p>Много курсов по востребованным направлениям. Найдите то, что подходит именно вам.</p>
    
    <div class="tags">
        <span class="badge-wheat">Программирование</span>
        <span class="badge-wheat">Игры</span>
        <span class="badge-wheat">Кино и Музыка</span>
        <span class="badge-wheat">Английский язык</span>
    </div>

    <div class="container-fluid">
        <div class="row my-2">
            <div class="col text-center">
                <h2>Как устроена платформа Online-Курс</h2>
            </div>
        </div>
    </div>
    <div class="row my-4 justify-content-center">
        <div class="col-10">
            <div class="card-deck">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">01. Круглосуточный доступ к личному кабинету</h5>
                        <p class="card-text">Смотрите видео онлайн в удобное время</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row my-4 justify-content-center">
        <div class="col-10">
            <div class="card-deck">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">02. Курсы обновляются регулярно</h5>
                        <p class="card-text">Получаете знания, которые отвечают требованиям рынка труда</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row my-4 justify-content-center">
        <div class="col-10">
            <div class="card-deck">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">03. Проверочные тесты и практические задания</h5>
                        <p class="card-text">Закрепляете теорию на практике и получаете обратную связь</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    

    <h3 class="mt-5">Основатели платформы</h3>
    <div class="row justify-content-center">
        <div class="col-3">
            <img src="{% static 'images/ivan.jpg' %}" class="img-fluid rounded-circle" alt="Иван Павлюченко">
            <h5>Иван Павлюченко</h5>
            <p>Основатель и генеральный директор Online-Курс.</p>
        </div>
        <div class="col-3">
            <img src="{% static 'images/anna.jpg' %}" class="img-fluid rounded-circle" alt="Анна Иванченко">
            <h5>Анна Иванченко</h5>
            <p>Основатель и программный директор Online-Курс.</p>
        </div>
        <div class="col-3">
            <img src="{% static 'images/petr.jpeg' %}" class="img-fluid rounded-circle" alt="Петр Карпин">
            <h5>Петр Карпин</h5>
            <p>Основатель и продуктовый директор Online-Курс.</p>
        </div>
    </div>
</div>
{% endblock %}

Web/templates/zxc/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Online-Курс{% endblock title %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            font-family: 'Prosto Sans', sans-serif;
        }
        header {
            background-color: wheat;
            color: black;
            padding: 20px;
            text-align: center;
            position: relative;
        }
        .promo-banner {
            background-color: #ffcc00;
            padding: 10px;
            text-align: center;
            font-weight: bold;
        }
        .header-links {
            display: flex;
            justify-content: space-between; /* Элементы в противоположные стороны */
            align-items: center;
            padding: 10px 20px;
            background-color: wheat; /* Белый фон */
            font-family: Arial black, sans-serif;
        }       
        .header-links a {
            margin-right: 10px;
            text-decoration: none;
            color: #333;
        }
        .tag-container {
            margin: 15px 0;
            display: flex;
            justify-content: center;
            flex-wrap: wrap;
            color: wheat;
        }
        .tag {
            background-color: wheat;
            border-radius: 20px;
            padding: 10px 15px;
            margin: 5px;
            color: #0073e6;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);
        }
        .dropdown-menu.show {
            display: block !important;
        }
        .dropdown .dropdown-menu a:hover {
            background-color: #f0f0f0;
        }
        .dropdown .btn {
            background-color: wheat; /* Цвет фона кнопки */
            color: #333; /* Цвет текста */
            border: none; /* Убираем рамку, если нужно */
        }
        .dropdown .btn:hover {
            background-color: wheat; /* Цвет фона кнопки при наведении (можете оставить wheat или выбрать чуть темнее) */
            color: #000; /* Цвет текста при наведении */
        }
        .navbar {
            display: flex;
            justify-content: space-between; /* Разделяет элементы на разных сторонах */
            align-items: center;
            padding: 10px 20px;
            background-color: wheat;
        }
        .navbar-left {
            display: flex;
            gap: 15px;
        }
        
        .navbar-right {
            display: flex;
            gap: 15px;

        }
        .navbar-left a {
            display: inline-block;
            padding: 10px 20px;
            font-size: 18px;
            font-weight: bold;
            color: #333; /* Цвет текста */
            text-decoration: none; /* Убираем подчеркивание */
            border: 2px solid #333; /* Чёрная обводка */
            border-radius: 10px; /* Скругленные углы */
            background-color: transparent; /* Прозрачный фон */
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); /* Лёгкая тень */
            transition: all 0.3s ease-in-out; /* Плавный переход эффектов */
        }
    </style>
</head>
<body>

<header>
    <div class="header-links d-flex justify-content-between">
    <div class="navbar">
        <div class="navbar-left">
            <a href="{% url 'home' %}">Online-Курс</a>
        </div>
    </div>
    <div class="navbar">
        <div class="navbar-right">
    <div class="header-links d-flex justify-content-between">
        <div class="dropdown d-inline-block">
            <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownCatalog" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="background-color: wheat; color: #333; border: 2px solid #333; border-radius: 10px; 
            text-transform: uppercase; font-weight: bold; box-shadow: 0px 4px 6px rgba(0,0,0,0.1); 
            transition: all 0.3s ease-in-out;">
                Каталог
            </a>
            <div class="dropdown-menu" aria-labelledby="dropdownCatalog">
                <a class="dropdown-item" href="{% url 'programming_courses' %}">Программирование</a>
                <a class="dropdown-item" href="{% url 'game_courses' %}">Игры</a>
                <a class="dropdown-item" href="{% url 'english_courses' %}">Ангийский язык</a>
                <a class="dropdown-item" href="{% url 'musicandcinema_courses' %}">Кино и Музыка</a>
            </div>
        </div>
    </div>
        </div>
    <div class="navbar">
        <div class="dropdown d-inline-block">
            <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownCatalog" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="background-color: wheat; color: #333; border: 2px solid #333; border-radius: 10px; 
            text-transform: uppercase; font-weight: bold; box-shadow: 0px 4px 6px rgba(0,0,0,0.1); 
            transition: all 0.3s ease-in-out;">
                О Online-курс
            </a>
            <div class="dropdown-menu" aria-labelledby="dropdownCatalog">
                <a class="dropdown-item" href="{% url 'about' %}">О нас</a>
                <a class="dropdown-item" href="{% url 'contact' %}">Контакты</a>
            </div>
        </div>
        </div>
        {% if user.is_authenticated %}
        <div class="header-links d-flex justify-content-between">
        <a href="{% url 'profile' %}" class="btn btn-secondary" style="background-color: wheat; color: #333; border: 2px solid #333; border-radius: 10px; 
        text-transform: uppercase; font-weight: bold; box-shadow: 0px 4px 6px rgba(0,0,0,0.1); 
        transition: all 0.3s ease-in-out;">Профиль</a>
        <!-- Кнопка "Выйти" -->
        <a href="{% url 'logout' %}" class="btn btn-secondary" style="background-color: wheat; color: #333; border: 2px solid #333; border-radius: 10px; 
        text-transform: uppercase; font-weight: bold; box-shadow: 0px 4px 6px rgba(0,0,0,0.1); 
        transition: all 0.3s ease-in-out;">Выйти</a>
        {% else %}
        <a href="{% url 'login' %}" class="btn btn-secondary" style="background-color: wheat; color: #333; border: 2px solid #333; border-radius: 10px; 
        text-transform: uppercase; font-weight: bold; box-shadow: 0px 4px 6px rgba(0,0,0,0.1); 
        transition: all 0.3s ease-in-out;">Войти</a>
        {% endif %}
        </div>
    </div>
    </div>
    </div>
</header>

<div class="container">
    {% block content %}{% endblock content %}
</div>

<footer>
    <p>Copyright &copy; 2024 Online-Курс, Все права защищены.</p>
</footer>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Web/templates/zxc/contact.html
{% extends "zxc/base.html" %}
<head>
{% load static %}
<style>
    .card {
        flex: 1 1 auto; /* Увеличивает гибкость ширины карточек */
        min-width: 300px; /* Минимальная ширина карточки */
    }
    .card-deck {
        gap: 20px; /* Расстояние между карточками */
    }
</style>
</head>
{% block content %}
<div class="container-fluid">
    <!-- Оглавление -->
    <div class="row my-2">
        <div class="col text-center">
            <h2>Контакты</h2>
        </div>
    </div>
    <!-- Название блока -->
    <div class="row my-2 text-primary text-center">
        <h3>{{ name }}</h3>
    </div>
    <div class="row my-2 text-muted text-center">
        <h4>{{ text_head }}</h4>
    </div>

    <!-- Блок контактов -->
    <div class="row my-4 justify-content-center">
        <div class="col-10">
            <div class="card-deck">
                <!-- Первый блок контактов -->
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Общие вопросы</h5>
                        <p class="card-text">Email: hello@online-course.ru</p>
                        <p class="card-text">Телефон: 8 (800) 123-45-67</p>
                        <p class="card-text">Вопросы по покупке, оплате и содержанию курсов</p>
                    </div>
                </div>

                <!-- Второй блок контактов -->
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Пресс-служба</h5>
                        <p class="card-text">Email: support@online-course.ru</p>
                        <p class="card-text">Телефон: +7 (495) 123-45-67</p>
                        <p class="card-text">Вопросы по учебному процессу, если вы уже проходите курс</p>
                    </div>
                </div>

                <!-- Третий блок контактов -->
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Редакция Online-курс</h5>
                        <p class="card-text">Email: info@media.online-course.ru</p>
                        <p class="card-text">Адрес: 119049, г. Москва, Ленинский пр., д. 6, стр. 20</p>
                        <p class="card-text">Почтовый адрес</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Web/templates/zxc/course_list.html
{% extends 'zxc/base.html' %}

{% block content %}
    <h1>Список курсов</h1>
    {% if courses %}
        <ul>
            {% for course in courses %}
                <li>
                    {{ course.title }} - {{ course.price }} руб.
                    <!-- Добавьте любые другие поля, которые хотите отобразить -->
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Курсы не найдены.</p>
    {% endif %}
{% endblock %}

Web/templates/zxc/course_list_student_user.html
{% extends 'zxc/base.html' %}

{% block content %}
<h1>Мои курсы</h1>

{% if courses %}
    <ul>
        {% for course in courses %}
        <li>
            <div style="border: 1px solid #ddd; padding: 15px; margin-bottom: 20px;">
                <h2>{{ course.title }}</h2>
                <p><strong>Категория:</strong> {{ course.get_categorycourse_display }}</p>
                <p><strong>Описание:</strong> {{ course.description }}</p>
                <p><strong>Стоимость:</strong> {{ course.price }} ₽</p>
                <p><strong>Длительность:</strong> {{ course.duration }}</p>
                {% if course.teacher.count > 0 %}
                    <p><strong>Преподаватели:</strong> 
                        {% for teacher in course.teacher.all %}
                            {{ teacher }}{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </p>
                {% endif %}
                <img src="{{ course.photo.url }}" alt="Обложка курса" style="max-width: 200px;">
            </div>
        </li>
        {% endfor %}
    </ul>
{% else %}
    <p>У вас нет взятых курсов.</p>
{% endif %}

{% endblock %}

Web/templates/zxc/english_courses.html
{% extends 'zxc/base.html' %}

{% block content %}
    <h1>Английский язык</h1>
    {% if courses %}
        <div class="courses-container">
            {% for course in courses %}
                <div class="course-item">
                    <h2>{{ course.title }}</h2>
                    {% if course.photo %}
                        <img src="{{ course.photo.url }}" alt="Обложка {{ course.title }}" class="course-image" width="200" height="200">
                    {% else %}
                        <p>Обложка недоступна.</p>
                    {% endif %}
                    
                    <button class="show-info-btn" onclick="toggleInfo('{{ forloop.counter }}')">Показать информацию</button>
                    
                    <div id="info-{{ forloop.counter }}" class="course-info" style="display: none;">
                        <p><strong>Описание:</strong> {{ course.description|default:"Нет описания" }}</p>
                        <p><strong>Преподаватели:</strong>
                            {% for teacher in course.teacher.all %}
                                {{ teacher.first_name }} {{ teacher.middle_name }} {{ teacher.last_name }}{% if not forloop.last %}, {% endif %}
                            {% empty %}
                                Преподаватели не указаны.
                            {% endfor %}
                        </p>
                        <p><strong>Длительность:</strong> {{ course.duration.duration|default:"-" }} месяцев</p>
                        <p><strong>Стоимость:</strong> {{ course.price|default:"-" }} руб.</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>Курсы по программированию пока не добавлены.</p>
    {% endif %}
    
    <script>
        function toggleInfo(courseId) {
            const infoBlock = document.getElementById(`info-${courseId}`);
            if (infoBlock.style.display === "none") {
                infoBlock.style.display = "block";
            } else {
                infoBlock.style.display = "none";
            }
        }
    </script>
{% endblock %}

Web/templates/zxc/game_courses.html
{% extends 'zxc/base.html' %}

{% block content %}
    <h1>Игры</h1>
    {% if courses %}
        <div class="courses-container">
            {% for course in courses %}
                <div class="course-item">
                    <h2>{{ course.title }}</h2>
                    {% if course.photo %}
                        <img src="{{ course.photo.url }}" alt="Обложка {{ course.title }}" class="course-image" width="200" height="200">
                    {% else %}
                        <p>Обложка недоступна.</p>
                    {% endif %}
                    
                    <button class="show-info-btn" onclick="toggleInfo('{{ forloop.counter }}')">Показать информацию</button>
                    
                    <div id="info-{{ forloop.counter }}" class="course-info" style="display: none;">
                        <p><strong>Описание:</strong> {{ course.description|default:"Нет описания" }}</p>
                        <p><strong>Преподаватели:</strong>
                            {% for teacher in course.teacher.all %}
                                {{ teacher.first_name }} {{ teacher.middle_name }} {{ teacher.last_name }}{% if not forloop.last %}, {% endif %}
                            {% empty %}
                                Преподаватели не указаны.
                            {% endfor %}
                        </p>
                        <p><strong>Длительность:</strong> {{ course.duration.duration|default:"-" }} месяцев</p>
                        <p><strong>Стоимость:</strong> {{ course.price|default:"-" }} руб.</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>Курсы по программированию пока не добавлены.</p>
    {% endif %}
    
    <script>
        function toggleInfo(courseId) {
            const infoBlock = document.getElementById(`info-${courseId}`);
            if (infoBlock.style.display === "none") {
                infoBlock.style.display = "block";
            } else {
                infoBlock.style.display = "none";
            }
        }
    </script>
{% endblock %}

Web/templates/zxc/index.html
{% extends "zxc/base.html" %}

{% block title %}Главная страница{% endblock %}

{% block header %}
Добро пожаловать на Online-курс
{% endblock %}

{% load static %}

{% block content %}
<body>
    <div class="full-width-image">
    <img src="{% static 'images/clouds.jpg' %}" width="900px" height="500px">
    </div>  
</body>
<section>
    <div class="about-section">
    <h1>О нас</h1>
    <p>
        Мы — команда профессионалов, которая помогает людям учиться. Наши курсы разработаны таким образом, чтобы вы могли получать знания комфортно
        и эффективно. Присоединяйтесь и начните своё путешествие в мир нового прямо сейчас!
    </p>
    </div>
</section>
<section>
    <div class="courses-section">
    <h2>Наши курсы</h2>
    <div class="buttons">
        <a href="{% url 'programming_courses' %}" class="button">Программирование</a>
        <a href="{% url 'english_courses' %}" class="button">Английский язык</a>
        <a href="{% url 'game_courses' %}" class="button">Игры</a>
        <a href="{% url 'musicandcinema_courses' %}" class="button">Кино и музыка</a>
    </div>
    </div>
</section>
<style>
    .buttons {
        display: flex;
        flex-direction: row; /* Кнопки по горизонтали */
        flex-wrap: wrap; /* Если кнопок больше, следующая строка */
        justify-content: center; /* Горизонтальное выравнивание */
        align-items: center; /* Вертикальное выравнивание */
    }
    .buttons .button {
        display: inline-block;
        padding: 10px 20px;
        margin: 5px;
        color: black;
        text-decoration: none;
        font-size: 16px;
        font-weight: bold;
        border: 2px solid wheat;
        border-radius: 25px;
        background-color: wheat;
        transition: background-color 0.3s, color 0.3s;
    }
    .buttons .button:hover {
        background-color: black;
        color: white;
    }
    body {
        margin: 0;
        padding: 0;
    }
    .about-section, .courses-section {
        width: 80%; /* Центральное выравнивание с ограничением по ширине */
        text-align: center;
        margin: 20px 0;
    }
    .full-width-image img{
        border-radius: 30%;
    }
</style>
{% endblock %}

Web/templates/zxc/login.html
{% extends 'zxc/base.html' %}

{% block title %}Вход{% endblock title %}

{% block content %}
<div class="container">
    <h2>Вход</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Войти</button>
    </form>
    <p>Нет аккаунта? <a href="{% url 'register' %}">Зарегистрироваться</a></p>
</div>
{% endblock %}

Web/templates/zxc/profile.html
{% extends 'zxc/base.html' %}

{% block content %}
<div class="container">
    <h2>Ваш Профиль</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Обновить</button>
    </form>
    <h3>Ваши Курсы</h3>
    <ul>
        {% for course in courses %}
            <li>{{ course.title }}</li>
        {% empty %}
            <li>У вас еще нет курсов.</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}